# Generated by Django 2.0.13 on 2019-03-31 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_den', models.DateField()),
                ('hora_den', models.TimeField()),
                ('edad', models.IntegerField()),
                ('sexo_vic', models.CharField(max_length=10)),
                ('cantdiad_vic', models.IntegerField()),
                ('id_arma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.Arma')),
                ('id_barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.Barrio')),
                ('id_empleado_vic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.Empleado')),
                ('id_escolaridad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.Escolaridad')),
                ('id_est_civ', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.Estado_Civil')),
                ('id_mov_agr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agresor', to='mapa.Movil')),
                ('id_mov_vic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='victima', to='mapa.Movil')),
                ('id_pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.Pais')),
                ('id_profesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.Profesion')),
                ('id_sitio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.Sitio')),
            ],
        ),
    ]
