# Generated by Django 2.0.13 on 2019-03-31 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0002_denuncia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='id_mov_agr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movil_agresor', to='mapa.Movil'),
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='id_mov_vic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movil_victima', to='mapa.Movil'),
        ),
    ]
