# Generated by Django 2.0.13 on 2019-05-04 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0005_auto_20190331_1512'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Delito',
        #     fields=[
        #         ('id_delito', models.IntegerField(primary_key=True, serialize=False)),
        #         ('nom_delito', models.CharField(max_length=50)),
        #     ],
        # ),
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice_criminalidad', models.DecimalField(decimal_places=4, max_digits=5)),
                ('indice_color', models.DecimalField(decimal_places=4, max_digits=5)),
                ('anio', models.IntegerField()),
                ('id_barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.Barrio')),
            ],
        ),
        # migrations.CreateModel(
        #     name='Sectores_Barrio',
        #     fields=[
        #         ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('distancia', models.IntegerField()),
        #         ('foco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='foco', to='mapa.Barrio')),
        #         ('segundo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='segundo', to='mapa.Barrio')),
        #     ],
        # ),
        migrations.RenameField(
            model_name='denuncia',
            old_name='cantdiad_vic',
            new_name='cantidad_vic',
        ),
        # migrations.AddField(
        #     model_name='denuncia',
        #     name='id_delito',
        #     field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='mapa.Delito'),
        #     preserve_default=False,
        # ),
    ]
