# Generated by Django 2.0.13 on 2019-05-04 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0006_auto_20190503_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice_criminalidad', models.DecimalField(decimal_places=4, max_digits=5)),
                ('indice_color', models.DecimalField(decimal_places=4, max_digits=5)),
                ('anio', models.IntegerField()),
                ('id_barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.Barrio')),
            ],
        ),
    ]
