# Generated by Django 2.0.13 on 2019-03-31 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id_arma', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_arma', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('id_bario', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_barrio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CoordenadasPoligono',
            fields=[
                ('latitud', models.CharField(max_length=20)),
                ('longitud', models.CharField(max_length=20)),
                ('id_coor_poli', models.BinaryField(primary_key=True, serialize=False)),
                ('id_barrio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.Barrio')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_dpto', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_dpto', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_empleado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridad',
            fields=[
                ('id_escolaridad', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_escolaridad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_est_civ', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_est_civ', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movil',
            fields=[
                ('id_movil', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_movil', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_muni', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nom_muni', models.CharField(max_length=50)),
                ('id_dpto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_pais', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id_profesion', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_profesion', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('id_sitio', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_sitio', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id_zona', models.IntegerField(primary_key=True, serialize=False)),
                ('nom_zona', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='barrio',
            name='id_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.Municipio'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='id_zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mapa.Zona'),
        ),
    ]
