# Generated by Django 2.0.13 on 2019-03-31 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0003_auto_20190331_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='id_pais',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
