# Generated by Django 2.0.13 on 2019-03-31 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0004_departamento_id_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='CoordenadasPoligono',
            name='id_coor_poli',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
